### PR TITLE
Allow download cluster

### LINKED ISSUE #69: Create Download Button for filtered selection
Create a download button that lets the user download the filtered clusters from the database (filter options are taken as query parameters).

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Fix #69

### CODE REVIEW

**Comment by christian-rli** [comment]
Nice, thanks for implementing the labels on the sliders! Commenting on functionality: The button appears to link to the website itself, with parameters in the URL. I assume this is to pass on the arguments to a function in python/flask. Is there a way to pass arguments without reloading the entire website or is the solution to adapt the URL, so that only the download will prompt?

**Comment by Bachibouzouk** [comment]
> Is there a way to pass arguments without reloading the entire website or is the solution to adapt the URL

I am on it :), now only the filtering with the DB remains to be done

**Comment by Bachibouzouk** [comment]
@christian-rli  - I think we can already merge this and implement the connection with the DB. The filter will have to be redefined anyway and the filling of the csv with the relevant information can be performed in a subsequent PR

**Comment by Bachibouzouk** [comment]
The follow up will be done in #96

**Pull request merged**
